// Generated by gencpp from file letsgoo/string_lengthResponse.msg
// DO NOT EDIT!


#ifndef LETSGOO_MESSAGE_STRING_LENGTHRESPONSE_H
#define LETSGOO_MESSAGE_STRING_LENGTHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace letsgoo
{
template <class ContainerAllocator>
struct string_lengthResponse_
{
  typedef string_lengthResponse_<ContainerAllocator> Type;

  string_lengthResponse_()
    : do_dai(0)  {
    }
  string_lengthResponse_(const ContainerAllocator& _alloc)
    : do_dai(0)  {
  (void)_alloc;
    }



   typedef int64_t _do_dai_type;
  _do_dai_type do_dai;





  typedef boost::shared_ptr< ::letsgoo::string_lengthResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::letsgoo::string_lengthResponse_<ContainerAllocator> const> ConstPtr;

}; // struct string_lengthResponse_

typedef ::letsgoo::string_lengthResponse_<std::allocator<void> > string_lengthResponse;

typedef boost::shared_ptr< ::letsgoo::string_lengthResponse > string_lengthResponsePtr;
typedef boost::shared_ptr< ::letsgoo::string_lengthResponse const> string_lengthResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::letsgoo::string_lengthResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::letsgoo::string_lengthResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::letsgoo::string_lengthResponse_<ContainerAllocator1> & lhs, const ::letsgoo::string_lengthResponse_<ContainerAllocator2> & rhs)
{
  return lhs.do_dai == rhs.do_dai;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::letsgoo::string_lengthResponse_<ContainerAllocator1> & lhs, const ::letsgoo::string_lengthResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace letsgoo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::letsgoo::string_lengthResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::letsgoo::string_lengthResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::letsgoo::string_lengthResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::letsgoo::string_lengthResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::letsgoo::string_lengthResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::letsgoo::string_lengthResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::letsgoo::string_lengthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3920ef61934e1d7324d841a8607eb6a6";
  }

  static const char* value(const ::letsgoo::string_lengthResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3920ef61934e1d73ULL;
  static const uint64_t static_value2 = 0x24d841a8607eb6a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::letsgoo::string_lengthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "letsgoo/string_lengthResponse";
  }

  static const char* value(const ::letsgoo::string_lengthResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::letsgoo::string_lengthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 do_dai\n"
;
  }

  static const char* value(const ::letsgoo::string_lengthResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::letsgoo::string_lengthResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.do_dai);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct string_lengthResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::letsgoo::string_lengthResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::letsgoo::string_lengthResponse_<ContainerAllocator>& v)
  {
    s << indent << "do_dai: ";
    Printer<int64_t>::stream(s, indent + "  ", v.do_dai);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LETSGOO_MESSAGE_STRING_LENGTHRESPONSE_H
